### PR TITLE
Ruby 3 compatibility

### PR DESCRIPTION
**Pull request by leamotta**
Ruby 3 introduces breaking changes when it comes to positional and keyword arguments https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

This PR adjusts the call to I18n#translate, using the splat operator (**) to send a set of keyword arguments instead of a hash.
Prevents the following error:
Screenshot 2023-02-06 at 17 26 26

### CODE REVIEW

**Comment by dblock** [comment]
We need to first put back CI (Travis is MIA) and add Ruby 3.x to the mix. Want to help? Maybe copy from https://github.com/mongoid/mongoid-grid_fs or https://github.com/mongoid/mongoid-locker?

**Comment by leamotta** [comment]
@dblock Thanks for the quick feedback! Have addressed this in the last commits. CI running green here https://github.com/leamotta/mongoid-scroll/actions

**Comment by dblock** [comment]
Looks great! Care to update https://github.com/mongoid/mongoid-scroll/blob/master/CHANGELOG.md please? Danger would complain but it only runs on PRs.

**Comment by dblock** [comment]
Btw, there are many projects in the mongoid org that could use similar help :)

Screen Shot 2023-02-12 at 10 22 22 AM

**Comment by leamotta** [comment]
@dblock Ready!

**Comment by dblock** [comment]
@leamotta Any interest in helping out with maintaining this library? If yes email me your rubygems login to dblock at dblock dot org.

**Pull request merged**
