### PR TITLE
Demonstrate (and fix?) problem scrolling by foreign key

### PR DESCRIPTION
**Pull request by joeyAghion**
@erikdstock and I encountered a problem scrolling by a `..._id` field. This is supported by the driver and database, but fails with `UnsupportedFieldTypeError` like:

    The type of the field 'publisher_id' is not supported: Object.

This is because calling (e.g.) `klass.fields['publisher_id'].type` returns `Object` despite the field actually containing a `BSON::ObjectId`.

Here's our attempt to fix this, but I'm not sure if we're accessing Mongoid's internals in the best manner.

### CODE REVIEW

**Comment by dblock** [comment]
Looks good.

For Danger would you mind changing CHANGELOG to have `###` in front of the releases, please, this came in a recent danger-changelog release.

**Comment by dblock** [comment]
Is the problem the version of mongo? 

Try this: https://github.com/mongoid/mongoid-history/blob/master/.travis.yml#L26

**Comment by joeyAghion** [comment]
Finally fixed via some work in `mongoid-compatibility` (https://github.com/mongoid/mongoid-compatibility/pull/10).

**Comment by dblock** [comment]
So do we still need that `precise` environment? What does it fix? Why aren't we selecting a specific version of MongoDB?

**Comment by joeyAghion** [comment]
Adding `dist: precise` did allow 2 of the matrix builds to succeed, but I haven't retried them after the compatibility fixes. Will try that now...

We certainly _can_ select a specific mongodb version, but that's independent of this issue/fix.

**Comment by joeyAghion** [comment]
In the above failed builds you can see that "natural" ordering seems to behave differently on `trusty` than on `precise`, even when the mongodb version is fixed.

How'd you like me to proceed? I'm not sure if there's a real platform-dependent bug here. In any case, it's independent of the original issue.

**Comment by dblock** [comment]
Alright, revert to `precise` that passes the specs and open an issue, I'll take a look.

**Pull request merged**
