### PR TITLE
Mongoid 7

### PR DESCRIPTION
**Pull request by asgerb**
Hey @dblock, everything runs green, so we should be good!
I added 7.0 to `.travis.yml` and made a small change in the `spec_helper.rb`.
Also cleaned up the Gemfile slightly, maybe a bit excessive but I hope it's OK 😉

### CODE REVIEW

**Comment by dblock** [comment]
Great! Just add CHANGELOG pls.

**Comment by asgerb** [comment]
Added CHANGELOG entry!

**Comment by dblock** [comment]
Thank you, merged. Since there're no code changes we technically don't need a release, but feel free to cut one.

**Comment by dblock** [comment]
I forgot one more place, we note versions in README ... pls add.

**Pull request merged**
